export type ValueFormater = {
    (value: number): string
}

export const twJustifyContentValues = [
    'justify-start',
    'justify-end',
    'justify-center',
    'justify-between',
    'justify-around',
    'justify-evenly',
] as const;

export type TwJustifyContent = typeof twJustifyContentValues[number];

export const twAlignItemsValues = [
    'items-start',
    'items-end',
    'items-center',
    'items-baseline',
    'items-stretch',
] as const;

export type TwAlignItems = typeof twAlignItemsValues[number];

export const twTextAlignmentValues = [
    'text-left',
    'text-center',
    'text-right',
    'text-justify',
    'text-start',
    'text-end',
] as const;

export type TwTextAlignment = typeof twTextAlignmentValues[number];

export const twMaxWidthValues = [
    'max-w-0',
    'max-w-none',
    'max-w-xs',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-6xl',
    'max-w-7xl',
    'max-w-full',
    'max-w-min',
    'max-w-max',
    'max-w-fit',
    'max-w-prose',
    'max-w-screen-sm',
    'max-w-screen-lg',
    'max-w-screen-xl',
    'max-w-screen-2xl',
] as const;

export type TwMaxWidth = typeof twMaxWidthValues[number];

export const twSpaceXValues = [
    'space-x-0',
    'space-x-0.5',
    'space-x-1',
    'space-x-1.5',
    'space-x-2',
    'space-x-2.5',
    'space-x-3',
    'space-x-3.5',
    'space-x-4',
    'space-x-5',
    'space-x-6',
    'space-x-7',
    'space-x-8',
    'space-x-9',
    'space-x-10',
    'space-x-11',
    'space-x-12',
    'space-x-14',
    'space-x-16',
    'space-x-20',
    'space-x-24',
    'space-x-28',
    'space-x-32',
    'space-x-36',
    'space-x-40',
    'space-x-44',
    'space-x-48',
    'space-x-52',
    'space-x-56',
    'space-x-60',
    'space-x-64',
    'space-x-72',
    'space-x-80',
    'space-x-96',
] as const;

export type TwSpaceX = typeof twSpaceXValues[number];

export const twTopMargins = [
    'mt-0',
    'mt-0.5',
    'mt-1',
    'mt-1.5',
    'mt-2',
    'mt-2.5',
    'mt-3',
    'mt-3.5',
    'mt-4',
    'mt-5',
    'mt-6',
    'mt-7',
    'mt-8',
    'mt-9',
    'mt-10',
    'mt-11',
    'mt-12',
    'mt-14',
    'mt-16',
    'mt-20',
    'mt-24',
    'mt-28',
    'mt-32',
    'mt-36',
    'mt-40',
    'mt-44',
    'mt-48',
    'mt-52',
    'mt-56',
    'mt-60',
    'mt-64',
    'mt-72',
    'mt-80',
    'mt-96',
] as const;

export type TwMarginTop = typeof twTopMargins[number];

export const twLeftPaddings = [
    'pl-0',
    'pl-0.5',
    'pl-1',
    'pl-1.5',
    'pl-2',
    'pl-2.5',
    'pl-3',
    'pl-3.5',
    'pl-4',
    'pl-5',
    'pl-6',
    'pl-7',
    'pl-8',
    'pl-9',
    'pl-10',
    'pl-11',
    'pl-12',
    'pl-14',
    'pl-16',
    'pl-20',
    'pl-24',
    'pl-28',
    'pl-32',
    'pl-36',
    'pl-40',
    'pl-44',
    'pl-48',
    'pl-52',
    'pl-56',
    'pl-60',
    'pl-64',
    'pl-72',
    'pl-80',
    'pl-96',
] as const;

export type TwPaddinLeft = typeof twLeftPaddings[number];

export const twRightPaddings = [
    'pr-0',
    'pr-0.5',
    'pr-1',
    'pr-1.5',
    'pr-2',
    'pr-2.5',
    'pr-3',
    'pr-3.5',
    'pr-4',
    'pr-5',
    'pr-6',
    'pr-7',
    'pr-8',
    'pr-9',
    'pr-10',
    'pr-11',
    'pr-12',
    'pr-14',
    'pr-16',
    'pr-20',
    'pr-24',
    'pr-28',
    'pr-32',
    'pr-36',
    'pr-40',
    'pr-44',
    'pr-48',
    'pr-52',
    'pr-56',
    'pr-60',
    'pr-64',
    'pr-72',
    'pr-80',
    'pr-96',
] as const;

export type TwPaddinRight = typeof twRightPaddings[number];

export const twTopPaddings = [
    'pt-0',
    'pt-0.5',
    'pt-1',
    'pt-1.5',
    'pt-2',
    'pt-2.5',
    'pt-3',
    'pt-3.5',
    'pt-4',
    'pt-5',
    'pt-6',
    'pt-7',
    'pt-8',
    'pt-9',
    'pt-10',
    'pt-11',
    'pt-12',
    'pt-14',
    'pt-16',
    'pt-20',
    'pt-24',
    'pt-28',
    'pt-32',
    'pt-36',
    'pt-40',
    'pt-44',
    'pt-48',
    'pt-52',
    'pt-56',
    'pt-60',
    'pt-64',
    'pt-72',
    'pt-80',
    'pt-96',
] as const;

export type TwPaddingTop = typeof twTopPaddings[number];

export const twBottomPaddings = [
    'pb-0',
    'pb-0.5',
    'pb-1',
    'pb-1.5',
    'pb-2',
    'pb-2.5',
    'pb-3',
    'pb-3.5',
    'pb-4',
    'pb-5',
    'pb-6',
    'pb-7',
    'pb-8',
    'pb-9',
    'pb-10',
    'pb-11',
    'pb-12',
    'pb-14',
    'pb-16',
    'pb-20',
    'pb-24',
    'pb-28',
    'pb-32',
    'pb-36',
    'pb-40',
    'pb-44',
    'pb-48',
    'pb-52',
    'pb-56',
    'pb-60',
    'pb-64',
    'pb-72',
    'pb-80',
    'pb-96',
] as const;

export type TwPaddingBottom = typeof twBottomPaddings[number];

export const twHeights = [
    'h-0',
    'h-0.5',
    'h-1',
    'h-1.5',
    'h-2',
    'h-2.5',
    'h-3',
    'h-3.5',
    'h-4',
    'h-5',
    'h-6',
    'h-7',
    'h-8',
    'h-9',
    'h-10',
    'h-11',
    'h-12',
    'h-14',
    'h-16',
    'h-20',
    'h-24',
    'h-28',
    'h-32',
    'h-36',
    'h-40',
    'h-44',
    'h-48',
    'h-52',
    'h-56',
    'h-60',
    'h-64',
    'h-72',
    'h-80',
    'h-96',
] as const;

export type TwHeight = typeof twHeights[number];

export const twWidths = [
    'w-0',
    'w-0.5',
    'w-1',
    'w-1.5',
    'w-2',
    'w-2.5',
    'w-3',
    'w-3.5',
    'w-4',
    'w-5',
    'w-6',
    'w-7',
    'w-8',
    'w-9',
    'w-10',
    'w-11',
    'w-12',
    'w-14',
    'w-16',
    'w-20',
    'w-24',
    'w-28',
    'w-32',
    'w-36',
    'w-40',
    'w-44',
    'w-48',
    'w-52',
    'w-56',
    'w-60',
    'w-64',
    'w-72',
    'w-80',
    'w-96',
] as const;

export type TwWidth = typeof twWidths[number];
