export const spacing = {
    none: {
        paddingLeft: 'pl-0',
        paddingTop: 'pt-0',
        paddingRight: 'pr-0',
        paddingBottom: 'pb-0',
        marginLeft: 'ml-0',
        marginTop: 'mt-0',
        marginRight: 'mr-0',
        marginBottom: 'mb-0',
        negativeMarginLeft: '-ml-0',
        negativeMarginRight: '-mr-0',
        left: 'left-0',
        right: 'right-0',
        top: 'top-0',
        bottom: 'bottom-0',
        spaceX: 'space-x-0',
    },
    threeXs: {
        paddingLeft: 'pl-0.5',
        paddingTop: 'pt-0.5',
        paddingRight: 'pr-0.5',
        paddingBottom: 'pb-0.5',
        marginLeft: 'ml-0.5',
        marginTop: 'mt-0.5',
        marginRight: 'mr-0.5',
        marginBottom: 'mb-0.5',
        negativeMarginLeft: '-ml-0.5',
        negativeMarginRight: '-mr-0.5',
        left: 'left-0.5',
        right: 'right-0.5',
        top: 'top-0.5',
        bottom: 'bottom-0.5',
        spaceX: 'space-x-0.5',
    },
    twoXs: {
        paddingLeft: 'pl-1',
        paddingTop: 'pt-1',
        paddingRight: 'pr-1',
        paddingBottom: 'pb-1',
        marginLeft: 'ml-1',
        marginTop: 'mt-1',
        marginRight: 'mr-1',
        marginBottom: 'mb-1',
        negativeMarginLeft: '-ml-1',
        negativeMarginRight: '-mr-1',
        left: 'left-1',
        right: 'right-1',
        top: 'top-1',
        bottom: 'bottom-1',
        spaceX: 'space-x-1',
    },
    xs: {
        paddingLeft: 'pl-1.5',
        paddingTop: 'pt-1.5',
        paddingRight: 'pr-1.5',
        paddingBottom: 'pb-1.5',
        marginLeft: 'ml-1.5',
        marginTop: 'mt-1.5',
        marginRight: 'mr-1.5',
        marginBottom: 'mb-1.5',
        negativeMarginLeft: '-ml-1.5',
        negativeMarginRight: '-mr-1.5',
        left: 'left-1.5',
        right: 'right-1.5',
        top: 'top-1.5',
        bottom: 'bottom-1.5',
        spaceX: 'space-x-1.5',
    },
    sm: {
        paddingLeft: 'pl-2',
        paddingTop: 'pt-2',
        paddingRight: 'pr-2',
        paddingBottom: 'pb-2',
        marginLeft: 'ml-2',
        marginTop: 'mt-2',
        marginRight: 'mr-2',
        marginBottom: 'mb-2',
        negativeMarginLeft: '-ml-2',
        negativeMarginRight: '-mr-2',
        left: 'left-2',
        right: 'right-2',
        top: 'left-2',
        bottom: 'bottom-2',
        spaceX: 'space-x-2',
    },
    md: {
        paddingLeft: 'pl-2.5',
        paddingTop: 'pt-2.5',
        paddingRight: 'pr-2.5',
        paddingBottom: 'pb-2.5',
        marginLeft: 'ml-2.5',
        marginTop: 'mt-2.5',
        marginRight: 'mr-2.5',
        marginBottom: 'mb-2.5',
        negativeMarginLeft: '-ml-2.5',
        negativeMarginRight: '-mr-2.5',
        left: 'left-2.5',
        right: 'right-2.5',
        top: 'top-2.5',
        bottom: 'bottom-2.5',
        spaceX: 'space-x-2.5',
    },
    lg: {
        paddingLeft: 'pl-3',
        paddingTop: 'pt-3',
        paddingRight: 'pr-3',
        paddingBottom: 'pb-3',
        marginLeft: 'ml-3',
        marginTop: 'mt-3',
        marginRight: 'mr-3',
        marginBottom: 'mb-3',
        negativeMarginLeft: '-ml-3',
        negativeMarginRight: '-mr-3',
        left: 'left-3',
        right: 'right-3',
        top: 'top-3',
        bottom: 'bottom-3',
        spaceX: 'space-x-3',
    },
    xl: {
        paddingLeft: 'pl-3.5',
        paddingTop: 'pt-3.5',
        paddingRight: 'pr-3.5',
        paddingBottom: 'pb-3.5',
        marginLeft: 'ml-3.5',
        marginTop: 'mt-3.5',
        marginRight: 'mr-3.5',
        marginBottom: 'mb-3.5',
        negativeMarginLeft: '-ml-3.5',
        negativeMarginRight: '-mr-3.5',
        left: 'left-3.5',
        right: 'right-3.5',
        top: 'top-3.5',
        bottom: 'bottom-3.5',
        spaceX: 'space-x-3.5',
    },
    twoXl: {
        paddingLeft: 'pl-4',
        paddingTop: 'pt-4',
        paddingRight: 'pr-4',
        paddingBottom: 'pb-4',
        marginLeft: 'ml-4',
        marginTop: 'mt-4',
        marginRight: 'mr-4',
        marginBottom: 'mb-4',
        negativeMarginLeft: '-ml-4',
        negativeMarginRight: '-mr-4',
        left: 'left-4',
        right: 'right-4',
        top: 'top-4',
        bottom: 'bottom-4',
        spaceX: 'space-x-4',
    },
    threeXl: {
        paddingLeft: 'pl-6',
        paddingTop: 'pt-6',
        paddingRight: 'pr-6',
        paddingBottom: 'pb-6',
        marginLeft: 'ml-6',
        marginTop: 'mt-6',
        marginRight: 'mr-6',
        marginBottom: 'mb-6',
        negativeMarginLeft: '-ml-6',
        negativeMarginRight: '-mr-6',
        left: 'left-6',
        right: 'right-6',
        top: 'top-6',
        bottom: 'bottom-6',
        spaceX: 'space-x-6',
    },
    fourXl: {
        paddingLeft: 'pl-8',
        paddingTop: 'pt-8',
        paddingRight: 'pr-8',
        paddingBottom: 'pb-8',
        marginLeft: 'ml-8',
        marginTop: 'mt-8',
        marginRight: 'mr-8',
        marginBottom: 'mb-8',
        negativeMarginLeft: '-ml-8',
        negativeMarginRight: '-mr-8',
        left: 'left-8',
        right: 'right-8',
        top: 'top-8',
        bottom: 'bottom-8',
        spaceX: 'space-x-8',
    },
};

export const twLeftPaddings = [
    'pl-0',
    'pl-0.5',
    'pl-1',
    'pl-1.5',
    'pl-2',
    'pl-2.5',
    'pl-3',
    'pl-3.5',
    'pl-4',
    'pl-5',
    'pl-6',
    'pl-7',
    'pl-8',
    'pl-9',
    'pl-10',
    'pl-11',
    'pl-12',
    'pl-14',
    'pl-16',
    'pl-20',
    'pl-24',
    'pl-28',
    'pl-32',
    'pl-36',
    'pl-40',
    'pl-44',
    'pl-48',
    'pl-52',
    'pl-56',
    'pl-60',
    'pl-64',
    'pl-72',
    'pl-80',
    'pl-96',
] as const;

export type TwPaddinLeft = typeof twLeftPaddings[number];

export const twRightPaddings = [
    'pr-0',
    'pr-0.5',
    'pr-1',
    'pr-1.5',
    'pr-2',
    'pr-2.5',
    'pr-3',
    'pr-3.5',
    'pr-4',
    'pr-5',
    'pr-6',
    'pr-7',
    'pr-8',
    'pr-9',
    'pr-10',
    'pr-11',
    'pr-12',
    'pr-14',
    'pr-16',
    'pr-20',
    'pr-24',
    'pr-28',
    'pr-32',
    'pr-36',
    'pr-40',
    'pr-44',
    'pr-48',
    'pr-52',
    'pr-56',
    'pr-60',
    'pr-64',
    'pr-72',
    'pr-80',
    'pr-96',
] as const;

export type TwPaddinRight = typeof twRightPaddings[number];

export const twTopPaddings = [
    'pt-0',
    'pt-0.5',
    'pt-1',
    'pt-1.5',
    'pt-2',
    'pt-2.5',
    'pt-3',
    'pt-3.5',
    'pt-4',
    'pt-5',
    'pt-6',
    'pt-7',
    'pt-8',
    'pt-9',
    'pt-10',
    'pt-11',
    'pt-12',
    'pt-14',
    'pt-16',
    'pt-20',
    'pt-24',
    'pt-28',
    'pt-32',
    'pt-36',
    'pt-40',
    'pt-44',
    'pt-48',
    'pt-52',
    'pt-56',
    'pt-60',
    'pt-64',
    'pt-72',
    'pt-80',
    'pt-96',
] as const;

export type TwPaddingTop = typeof twTopPaddings[number];


export const twBottomPaddings = [
    'pb-0',
    'pb-0.5',
    'pb-1',
    'pb-1.5',
    'pb-2',
    'pb-2.5',
    'pb-3',
    'pb-3.5',
    'pb-4',
    'pb-5',
    'pb-6',
    'pb-7',
    'pb-8',
    'pb-9',
    'pb-10',
    'pb-11',
    'pb-12',
    'pb-14',
    'pb-16',
    'pb-20',
    'pb-24',
    'pb-28',
    'pb-32',
    'pb-36',
    'pb-40',
    'pb-44',
    'pb-48',
    'pb-52',
    'pb-56',
    'pb-60',
    'pb-64',
    'pb-72',
    'pb-80',
    'pb-96',
] as const;

export type TwPaddingBottom = typeof twBottomPaddings[number];

export const twTopMargins = [
    'mt-0',
    'mt-0.5',
    'mt-1',
    'mt-1.5',
    'mt-2',
    'mt-2.5',
    'mt-3',
    'mt-3.5',
    'mt-4',
    'mt-5',
    'mt-6',
    'mt-7',
    'mt-8',
    'mt-9',
    'mt-10',
    'mt-11',
    'mt-12',
    'mt-14',
    'mt-16',
    'mt-20',
    'mt-24',
    'mt-28',
    'mt-32',
    'mt-36',
    'mt-40',
    'mt-44',
    'mt-48',
    'mt-52',
    'mt-56',
    'mt-60',
    'mt-64',
    'mt-72',
    'mt-80',
    'mt-96',
] as const;

export type TwMarginTop = typeof twTopMargins[number];
