export const spacing = {
    threeXs: {
        paddingLeft: 'pl-0.5',
        paddingTop: 'pt-0.5',
        paddingRight: 'pr-0.5',
        paddingBottom: 'pb-0.5',
        marginLeft: 'ml-0.5',
        marginTop: 'ml-0.5',
        marginRight: 'ml-0.5',
        marginBottom: 'ml-0.5',
    },
    twoXs: {
        paddingLeft: 'pl-1',
        paddingTop: 'pt-1',
        paddingRight: 'pr-1',
        paddingBottom: 'pb-1',
        marginLeft: 'ml-1',
        marginTop: 'ml-1',
        marginRight: 'ml-1',
        marginBottom: 'ml-1',
    },
    xs: {
        paddingLeft: 'pl-1.5',
        paddingTop: 'pt-1.5',
        paddingRight: 'pr-1.5',
        paddingBottom: 'pb-1.5',
        marginLeft: 'ml-1.5',
        marginTop: 'ml-1.5',
        marginRight: 'ml-1.5',
        marginBottom: 'ml-1.5',
    },
    sm: {
        paddingLeft: 'pl-2',
        paddingTop: 'pt-2',
        paddingRight: 'pr-2',
        paddingBottom: 'pb-2',
        marginLeft: 'ml-2',
        marginTop: 'ml-2',
        marginRight: 'ml-2',
        marginBottom: 'ml-2',
    },
    md: {
        paddingLeft: 'pl-2.5',
        paddingTop: 'pt-2.5',
        paddingRight: 'pr-2.5',
        paddingBottom: 'pb-2.5',
        marginLeft: 'ml-2.5',
        marginTop: 'ml-2.5',
        marginRight: 'ml-2.5',
        marginBottom: 'ml-2.5',
    },
    lg: {
        paddingLeft: 'pl-3',
        paddingTop: 'pt-3',
        paddingRight: 'pr-3',
        paddingBottom: 'pb-3',
        marginLeft: 'ml-3',
        marginTop: 'ml-3',
        marginRight: 'ml-3',
        marginBottom: 'ml-3',
    },
    xl: {
        paddingLeft: 'pl-3.5',
        paddingTop: 'pt-3.5',
        paddingRight: 'pr-3.5',
        paddingBottom: 'pb-3.5',
        marginLeft: 'ml-3.5',
        marginTop: 'ml-3.5',
        marginRight: 'ml-3.5',
        marginBottom: 'ml-3.5',
    },
    twoXl: {
        paddingLeft: 'pl-4',
        paddingTop: 'pt-4',
        paddingRight: 'pr-4',
        paddingBottom: 'pb-4',
        marginLeft: 'ml-4',
        marginTop: 'ml-4',
        marginRight: 'ml-4',
        marginBottom: 'ml-4',
    },
};
