import { ButtonColorTypes, ButtonProportionTypes, ButtonShapeTypes } from '@common/common-types';
import colorTheme, { defaultColors } from '@utils/colorTheme';
import { BaseColors } from '@utils/objects';
import { getColorVariantsFromColorThemeValue } from '@utils/classname-utils';

export const buttonProportions: {[char: string]: ButtonProportionTypes} = {
    xs: {
        paddingX: 'px-2.5',
        paddingY: 'py-1.5',
        textSize: 'text-xs',
    },
    sm: {
        paddingX: 'px-4',
        paddingY: 'py-2',
        textSize: 'text-sm',
    },
    md: {
        paddingX: 'px-4',
        paddingY: 'py-2',
        textSize: 'text-base',
    },
    lg: {
        paddingX: 'px-4',
        paddingY: 'py-2.5',
        textSize: 'text-lg',
    },
};

export const buttonShape: ButtonShapeTypes = {
    rounded: 'rounded-lg',
    border: '',
    shadow: ''
};

export const buttonColors: {[baseColor: string]: ButtonColorTypes} = {
    'slate': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Slate].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Slate].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Blue].ring).focusRingColor,
    },
    'gray': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Gray].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Gray].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Gray].ring).focusRingColor,
    },
    'zinc': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Zinc].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Zinc].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Zinc].ring).focusRingColor,
    },
    'neutral': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Neutral].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Neutral].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Neutral].ring).focusRingColor,
    },
    'stone': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Stone].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Stone].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Stone].ring).focusRingColor,
    },
    'red': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Red].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Red].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Red].ring).focusRingColor,
    },
    'orange': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Orange].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Orange].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Orange].ring).focusRingColor,
    },
    'amber': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Amber].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Amber].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Amber].ring).focusRingColor,
    },
    'yellow': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Yellow].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Yellow].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Yellow].ring).focusRingColor,
    },
    'lime': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Lime].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Lime].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Lime].ring).focusRingColor,
    },
    'green': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Green].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Green].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Green].ring).focusRingColor,
    },
    'emerald': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Emerald].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Emerald].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Emerald].ring).focusRingColor,
    },
    'teal': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Teal].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Teal].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Teal].ring).focusRingColor,
    },
    'cyan': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Cyan].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Cyan].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Cyan].ring).focusRingColor,
    },
    'sky': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Sky].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Sky].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Sky].ring).focusRingColor,
    },
    'blue': {
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Blue].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Blue].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Blue].ring).focusRingColor,
    },
    'indigo': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Indigo].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Indigo].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Indigo].ring).focusRingColor,
    },
    'violet': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Violet].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Violet].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Violet].ring).focusRingColor,
    },
    'purple': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Purple].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Purple].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Purple].ring).focusRingColor,
    },
    'fuchsia': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Fuchsia].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Fuchsia].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Fuchsia].ring).focusRingColor,
    },
    'pink': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Pink].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Pink].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Pink].ring).focusRingColor,
    },
    'rose': { 
        textColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Rose].text).textColor,
        hoverTextColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Rose].darkText).hoverTextColor,
        bgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).bgColor,
        hoverBgColor: getColorVariantsFromColorThemeValue(defaultColors['transparent']).hoverBgColor,
        borderColor: '',
        hoverBorderColor: '',
        focusRingColor: getColorVariantsFromColorThemeValue(colorTheme[BaseColors.Rose].ring).focusRingColor,
    }
};
